---
kind: pipeline
type: docker
name: build-and-push

steps:
- name: build www-cache
  image: plugins/docker
  settings:
    registry: registry.hayl.in
    repo: registry.hayl.in/www-cache
    target: www-cache
    tags:
      - "${DRONE_BRANCH}"
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - COMMIT=${DRONE_COMMIT_SHA}
    - REF=${DRONE_COMMIT_REF}
    - TIME=${DRONE_BUILD_STARTED}
    cache_from:
      - "registry.hayl.in/www-cache:${DRONE_BRANCH}"
- name: build www
  image: plugins/docker
  settings:
    registry: registry.hayl.in
    repo: registry.hayl.in/www
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - COMMIT=${DRONE_COMMIT_SHA}
    - REF=${DRONE_COMMIT_REF}
    - TIME=${DRONE_BUILD_STARTED}
    cache_from:
      - "registry.hayl.in/www-cache:${DRONE_BRANCH}"
- name: rollout
  image: haylinmoore/drone-rollout-restart:latest
  pull: always
  settings:
    deployment: haylinmoore
    namespace: default
    kubernetes_server:
      from_secret: kubernetes_server # Pulling these from secrets isn't required, but strongly encouraged
    kubernetes_token:
      from_secret: kubernetes_token
trigger:
  branch:
    - main
