kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./target
        - /usr/local/cargo
  - name: build
    image: rust:1-slim-bookworm
    commands:
      - cargo build --release --verbose

  - name: build-and-push-docker
    image: plugins/docker
    settings:
      registry: registry.hayl.in
      repo: registry.hayl.in/www
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - COMMIT=${DRONE_COMMIT_SHA}
        - REF=${DRONE_COMMIT_REF}
        - TIME=${DRONE_BUILD_STARTED}

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      ttl: 21
      mount:
        - ./target
        - /usr/local/cargo

  - name: rollout
    image: haylinmoore/drone-rollout-restart:latest
    pull: always
    settings:
      deployment: haylinmoore
      namespace: default
      kubernetes_server:
        from_secret: kubernetes_server
      kubernetes_token:
        from_secret: kubernetes_token

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - main
