---
kind: pipeline
type: docker
name: build-and-push

steps:
- name: build-and-push
  image: plugins/docker
  settings:
    registry: registry.hayl.in
    repo: registry.hayl.in/www
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
    - main
